#!/bin/bash

output_path=lib/binding_rust/bindings.rs
header_path='lib/include/tree_sitter/api.h'
block_type_underscores="--blocklist-type ^__.*"
if echo "#include <bits/stdint-uintn.h>" | 2>/dev/null cc -c -o /dev/null -xc - ; then
  block_type_underscores=""
fi

bindgen                                        \
  --size_t-is-usize                            \
  --no-layout-tests                            \
  --whitelist-type '^TS.*'                     \
  --whitelist-function '^ts_.*'                \
  --opaque-type FILE                           \
  --blocklist-type FILE                        \
  $block_type_underscores                      \
  --blocklist-function ts_tree_print_dot_graph \
  --size_t-is-usize                            \
  $header_path > $output_path

echo "" >> $output_path

defines=(
  TREE_SITTER_LANGUAGE_VERSION
  TREE_SITTER_MIN_COMPATIBLE_LANGUAGE_VERSION
)

for define in ${defines[@]}; do
  define_value=$(egrep "#define $define (.*)" $header_path | cut -d' ' -f3)
  echo "pub const $define: usize = $define_value;" >> $output_path
done
